<a href="https://colab.research.google.com/github/bhavani-018/Python-Practice/blob/main/python_interview_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

13-10-25

In [ ]:
# reverse a string
word="Dhoni loves india"
a=word.split()
a.reverse()
print(a)
print(" ".join(a))


['india', 'loves', 'Dhoni']
india loves Dhoni


In [ ]:
# Problem Statement

# Given an absolute path for a file (Unix-style), simplify it.

# A . means current directory.

# A .. means move up one directory.

# Multiple consecutive slashes / are treated as a single /.

# The result must always start with a single / and not end with a trailing slash (unless it’s just the root).
# Input: "/a/./b/../../c/" Output: "/c"

a="a/./b/../../c/"
b=a.split("/")
print(b)
l=[]
for i in b:
  if i=="" or i==".":
    continue
  elif i=="..":
    if l:
      l.pop()
  else:
   l.append(i)
  print(l)
print("/"+"/".join(l))





['a', '.', 'b', '..', '..', 'c', '']
['a']
['a', 'b']
['a']
[]
['c']
/c


In [ ]:
words = ["eat", "tea", "tan", "ate", "nat", "bat"]

d={}
for i in words:

12-10-25


In [1]:

arr = [0, 1, 2, 0, 1, 2]
print(sorted(arr))
a=arr.sort()
print(a)

[0, 0, 1, 1, 2, 2]
None


In [ ]:
arr=[0,1,4,3,8,2]
for i in range(0,len(arr)-1):
  for j in range(i,len(arr)-1):
    if arr[j]<arr[j+1]:
      continue
    elif arr[j]>arr[j+1]:
      arr[j],arr[j+1]=arr[j+1],arr[j]
  print(arr)
print(arr)

[0, 1, 3, 4, 2, 8]
[0, 1, 3, 2, 4, 8]
[0, 1, 2, 3, 4, 8]
[0, 1, 2, 3, 4, 8]
[0, 1, 2, 3, 4, 8]
[0, 1, 2, 3, 4, 8]


**python interview questions**
**1-08-2025**

In [ ]:
#Reverse a string
a="bhavani"
print(a[::-1])

inavahb


In [ ]:
#reverse a number
a=5674
rev=0
while a>0:
  lastdigit=a%10
  rev=rev*10 + lastdigit
  a//=10
print(rev)

4765


In [ ]:
#check palindrome
# a="malayalam"
a="welcome"
if a==a[::-1]:
    print('palindrom')
else:
    print('not palindrome')

not palindrome


In [ ]:
year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a Leap Year")
else:
    print(f"{year} is NOT a Leap Year")


Enter a year: 2024
2024 is a Leap Year


In [ ]:
#factorial
def fact(n):
  if n==0 or n==1:
    return 1
  else:
    return n*fact(n-1)
print(fact(5))

120


In [ ]:
#fizzbuzz
n=int(input("enter the num:"))
if n%3==0 and n%5==0:
  print("fizzbuzz")
elif n%3==0:
  print('fizz')
elif n%5==0:
  print('buzz')
else:
  print(n)

enter the num:17
17


In [ ]:
#to find max
a=[1,3,5,6]
large=a[0]
for i in a:
  if i>large:
    large=i
print(large)
#print(max(a))


6


In [ ]:
#to print the count of vowels:
sent="i woke up at six"
count=0
for c in sent:
  if c in 'aeiou':
    count+=1
print(count)

6


In [ ]:
#to remove duplicates

# def remove_duplicates(lst):
#     return (set(lst))

# print(remove_duplicates([1, 2, 2, 3]))

a=[3,4,6,6,6,5,4]
print(list(set(a)))

[3, 4, 5, 6]


In [ ]:
#list operations
a=[3,4,5,5]
a.append(8)
a=a+[6,7,8]
del(a[2])
a.insert(0,2)
print(a)

[2, 3, 4, 5, 8, 6, 7, 8]


In [ ]:
#fibonaci
def fibo(n):
  a=0
  b=1
  res=[]
  for i in range(n):
    res.append(a)
    a,b=b,a+b
  return res
print(fibo(5))

[0, 1, 1, 2, 3]


In [ ]:
#prime check
def prime(n):
  if n<=1:
    return "not prime"
  for i in range(2,int(n**0.5)+1):
    if n%i==0:
      return "not prime"
  return "prime"
print(prime(4))



not prime


In [ ]:
#to find sec largest
a=[1,1,1,1,1]
n=len(a)
first=a[0]
sec=-1
for i in range(n):
    if a[i]>=first:
        first=a[i]
print(first)

for i in range(n):
    if a[i]>=sec and a[i]!=first:
        sec=a[i]
print(sec)

# first=sec=-1
# for i in range(len(a)):
#   if a[i]>first:
#     sec=first
#     first=a[i]
#   elif a[i]>sec and a[i]!=first:
#     sec=a[i]
# print(first,sec)

1
-1


In [ ]:
#to print sum of elements
a=[4,7,2,10]
summ=0
for i in a:
  summ+=i
print(summ)

23


In [ ]:
#armstrong number
a=563
n=len(str(a))
temp=a
summ=0
while temp>0:
  digit=temp%10
  summ+=digit**n
  temp//=10
if a==summ:
  print("armstrong")
else:
  print("not armstrong")




not armstrong


In [ ]:
n=5
for i in range(n):
  for j in range(n):
    print('*',end=' ')
  print()
# print()


* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
#righthnd
n=5
for i in range(n):
  for j in range(i,n):
    print(' ',end='')
  for j in range(i+1):
     print('*',end='')
  print()




     *
    **
   ***
  ****
 *****


In [ ]:
n=6
for i in range(n):
  for j in range(i,n):
    print("*",end=' ')
  print()

* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
n=5
for i in range(n+1):
  for j in range(0,i):
    print(i,end=' ')
  print()


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
n=5
for i in range(n+1):
  for j in range(1,n-i+1):
    print(j,end=' ')
  print()

1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 



In [ ]:
n=5
for i in range(n+1):
  for j in range(n-i+1):
    print("*",end="")
  print()

******
*****
****
***
**
*


In [ ]:
n=5
for i in range(n):
  for j in range(n-i+1):
    print(" ",end='')
  for j in range((2*i)+1):
    print("*",end="")
  for j in range(n-i+1):
    print(" ",end='')
  print()

      *      
     ***     
    *****    
   *******   
  *********  


In [ ]:
n=5
for i in range(n):
  for j in range(i):
    print(" ",end='')
  for j in range(2*n-((2*i)+1)):
    print("*",end='')
  for j in range(i):
    print(" ",end='')
  print()

*********
 ******* 
  *****  
   ***   
    *    


In [ ]:
n = 5  # size of the pyramid

# Upper pyramid
for i in range(n):
    print(" " * (n-i-1) + "*" * (2*i+1))

# Lower inverted pyramid
for i in range(n-2, -1, -1):
    print(" " * (n-i-1) + "*" * (2*i+1))



    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *


In [ ]:
n=5

# Upper pyramid
for i in range(n):
  for j in range(n-i-1):           # left spaces
    print(" ",end='')
  for j in range((2*i)+1):         # stars
    print("*",end="")
  for j in range(n-i-1):           # right spaces
    print(" ",end='')
  print()

# Lower pyramid
for i in range(n):
  for j in range(i):               # left spaces
    print(" ",end='')
  for j in range(2*n-((2*i)+1)):   # stars
    print("*",end='')
  for j in range(i):               # right spaces
    print(" ",end='')
  print()


    *    
   ***   
  *****  
 ******* 
*********
*********
 ******* 
  *****  
   ***   
    *    


In [ ]:
def print_x_pattern(s):
    n = len(s)
    for i in range(n):
        line = [' '] * n  # Initialize line with spaces
        line[i] = s[i]  # Left to right
        line[n - i - 1] = s[n - i - 1]  # Right to left
        print(''.join(line))

print("Eg 1: Input: 12345")
print("Output:")
print_x_pattern("12345")

Eg 1: Input: 12345
Output:
1   5
 2 4 
  3  
 2 4 
1   5


In [ ]:
#Write a simple class in Python called Employee that has attributes name and salary, and a method to display them.

# class Employee:
#   def __init__(self,name,salary):
#     self.nameofperson=name
#     self.salaryofperson=salary
# obj=Employee("bhava",50000)
# print(obj.nameofperson)
# print(obj.salaryofperson)

class Employee:
  def __init__(self,name,salary):
    self.namee=name
    self.salaryy=salary

  def displayy(self):
    print(f"name: {self.namee} and salary :{self.salaryy}")

obj=Employee("bhava",50000)
obj.displayy()



name: bhava and salary :50000


In [ ]:
# #to find gcd
n1=45
n2=15
def gcd(n1,n2):
  while n2!=0:
    n1,n2=n2,n1%n2
  return n1
print(gcd(n1,n2))

# import math
# n1=12
# n2=14
# print(math.gcd(n1,n2))


15


In [ ]:
#remove duplicates in a list-sorted array
lst=[4,7, 5, 4, 6, 7, 5, 8, 7]
result=[]
for i in lst:
  if i not in result:
    result.append(i)
print(sorted(result))

[4, 5, 6, 7, 8]


In [ ]:
#nested loop
n=[[1,2],[3,4],[5,6]]
res=[]
for i in n:
  for j in i:
    res.append(j)
print(res)



[1, 2, 3, 4, 5, 6]


In [ ]:
#rotate the array bu k position
arr=[1,5,3,2,6]
n=len(arr)
k=7
k=k%n
print(arr[k:]+arr[:k])

[3, 2, 6, 1, 5]


In [ ]:
#to print gcd
n1=12
n2=14
n1=abs(n1)
n2=abs(n2)
def gcdd(n1,n2):
  while n2!=0:
    n1,n2=n2,n1%n2
  return n1

def lcmm(n1,n2):
  if n1==0 and n2==0:
    return 0
  else:
   return abs(n1*n2) // gcdd(n1,n2)

print(gcdd(n1,n2))
print(lcmm(n1,n2))



2
84


In [ ]:
#to reverse a list
lst=[1,2,3,4,5]
print(lst[::-1])

[5, 4, 3, 2, 1]


In [ ]:
#to check anagram
a="eat"
b="ate"
if sorted(a)==sorted(b):
  print("anagram")
else:
  print("not anagram")

anagram


**2pointers/sliding window**

In [ ]:
#print subarrays with sum<5 condition
# arr=[1,2,3,4]
# k=5
#bruteforce
def subarray(arr):
  n=len(arr)
  res=[]
  n=len(arr)
  for i in range(n):
    for j in range(i,n):
      reslt=arr[i:j+1]
      res.append(reslt)
  # print(res)
  return res
def findsum(res):
  maxx=0
  summm=[]
  for k in res:
    summ=sum(k)
    if summ>maxx:
      maxx=summ
      summm=k

    # summm.append(summ)
  return maxx,summm

arr=[1,2,3,4]
res=subarray(arr)
print(res)
print(findsum(res))

[[1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [2], [2, 3], [2, 3, 4], [3], [3, 4], [4]]
(10, [1, 2, 3, 4])


In [ ]:
# arr=[1,2,3,4]
# k=5
#bruteforce
def subarray(arr):
  n=len(arr)
  res=[]
  n=len(arr)
  for i in range(n):
    for j in range(i,n):
      reslt=arr[i:j+1]
      print(reslt)
      res.append(reslt)
print(subarray([1,2,3,4]))

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[2]
[2, 3]
[2, 3, 4]
[3]
[3, 4]
[4]
None


In [ ]:
#create a function print_area() that calls the area() method of any object.Create two classes Circle and Rectangle with different area() implementations.

class square:
  def __init__(self,side):
    self.a=side
  def area(self):
    print(self.a*self.a)

class rectangle:
  def __init__(self,length,width):
    self.l=length
    self.w=width
  def area(self):
    print(self.l*self.w)

def print_area(shape):
  shape.area()

obj1=square(2)
obj2=rectangle(2,3)
print_area(obj1)
print_area(obj2)

4
6


In [ ]:
#Write a function animal_sound() that calls make_sound() of any object. Create Dog and Cat classes with different make_sound() methods.

class Dog:
  def make_sound(self):
    print("loll")
class Cat:
  def make_sound(self):
    print("meoww")

def animal_sound(s):
  s.make_sound()

obj1=Dog()
obj2=Cat()
animal_sound(obj1)
animal_sound(obj2)


loll
meoww


In [ ]:
#Write a function start_engine() that calls the engine() method of any object passed to it.
#Create two classes Car and Motorbike that implement engine() differently and test with both.

def start_engine(self):
  self.engine()

class Car:
  def engine(self):
    print("car started")
class Motorbike:
  def engine(self):
    print("motorbike started")

obj1=Car()
obj2=Motorbike()
start_engine(obj1)

car started


In [ ]:
#Create a function process_payment() that calls pay() method of any object.
#Create two classes CreditCardPayment and PayPalPayment that implement pay() differently.
def process_payment(self,amount):
    self.pay(amount)
class creditcardpayment:
    def pay(self,amount):
        print(f"pay with creditcard {amount}")
class paypalpayment:
    def pay(self,amount):
        print(f"pay with paypal {amount}")
obj1=creditcardpayment()
obj2=paypalpayment()
process_payment(obj1,1000)
process_payment(obj2,2000)



pay with creditcard 1000
pay with paypal 2000


In [ ]:
# Create a function play_media() that calls play() method of any object.
# Create two classes MP3Player and VideoPlayer with different play() outputs.
# Call play_media() with each object.
def play_media(self):
    self.play()
class mp3player:
    def play(self):
        print("play song")
class videoplayer:
    def play(self):
        print("play video")
obj1=mp3player()
obj2=videoplayer()
play_media(obj1)
play_media(obj2)

play song
play video


In [ ]:
def play_media(self,media):
  self.play(media)
class mp3player:
  def play(self,media):
    print (f"play {media}")
class videoplayer:
  def play(self,media):
    print (f"play {media}")
obj1=mp3player()
obj2=videoplayer()
play_media(obj1,"song")
play_media(obj2,"video")


play song
play video


In [ ]:
# Base class
class Animal:
    def sound(self):
        print("Animals make sounds")

# Child class Dog
class Dog(Animal):
    def sound(self):
        print("Dog says Woof!")

# Child class Cat
class Cat(Animal):
    def sound(self):
        print("Cat says Meow!")

# Testing
d = Dog()
c = Cat()
Animal.sound(d)
d.sound()   # Dog says Woof!
c.sound()   # Cat says Meow!


Animals make sounds
Dog says Woof!
Cat says Meow!


In [ ]:
# Base class
class Vehicle:
    def fuel_type(self):
        print("Different vehicles use different fuel types.")

# Child class Car
class Car(Vehicle):
    def fuel_type(self):
        print("Car uses Petrol or Diesel.")

# Child class Bike
class Bike(Vehicle):
    def fuel_type(self):
        print("Bike uses Petrol.")

# Testing
# v = Vehicle()
c = Car()
b = Bike()

# v.fuel_type()   # From base class
c.fuel_type()   # From Car
b.fuel_type()   # From Bike


Car uses Petrol or Diesel.
Bike uses Petrol.


In [ ]:
# Base class
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    def details(self):
        print(f"Employee: {self.name}, Salary: {self.salary}")

# Manager class
class Manager(Employee):
    def work(self):
        print(f"{self.name} manages the team.")

# Developer class
class Developer(Employee):
    def work(self):
        print(f"{self.name} writes code.")

# Testing
m = Manager("Alice", 80000)
d = Developer("Bob", 60000)

# m.details()
m.work()

d.details()
d.work()


Alice manages the team.
Employee: Bob, Salary: 60000
Bob writes code.


In [ ]:
class BankAccount:
  def __init__(self,balance,account_no):
    self.__balance=balance
    self.__account_no=account_no

  def deposit(self,amount):
    print(f"deposit amount:{amount}")
  def withdraw(self,amount):
    print(f"withdraw amount:{amount}")
  def get_balance(self):
    return self.__balance

obj1=BankAccount(5000,123)
obj1.deposit(2000)
obj1.withdraw(1000)
obj1.get_balance()

deposit amount:2000
withdraw amount:1000


5000

In [ ]:
class Student:
    def __init__(self, name, roll_no, marks):
        self.__name = name      # private
        self.__roll_no = roll_no  # private
        self.__marks = marks    # private

    # Getter and Setter
    def set_marks(self, marks):
        if 0 <= marks <= 100:
            self.__marks = marks
        else:
            print("Invalid marks!")

    def get_marks(self):
        return self.__marks

    def is_passed(self):
        return self.__marks >= 40


# Example
s = Student("John", 101, 35)
print("Passed:", s.is_passed())
s.set_marks(75)
print("Marks:", s.get_marks())
print("Passed:", s.is_passed())


Passed: False
Marks: 75
Passed: True


**practise interview POV questions** 14/9/25

In [ ]:
for i in range(3):
  for j in range(i):
    print(i)
print()

1
2
2



In [ ]:
n=0
while n<10:
  print(n)
  n+=1

0
1
2
3
4
5
6
7
8
9


In [ ]:
j=2
n=10
for i in range(1,n+1):
  print(i,'*',j,'=',i*j)

1 * 2 = 2
2 * 2 = 4
3 * 2 = 6
4 * 2 = 8
5 * 2 = 10
6 * 2 = 12
7 * 2 = 14
8 * 2 = 16
9 * 2 = 18
10 * 2 = 20


In [ ]:
n = 5
for i in range(1, 11):
    print(n, "x", i, "=", n*i)


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [ ]:
n=5
for i in range(n+1):
  for j in range(i):
    print('*',end=" ")
  print()


* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
a=[1,2,3,3,4,5,5,6]
res=[]
for i in a:
  if i not in res:
    res.append(i)
print(res)

[1, 2, 3, 4, 5, 6]


In [ ]:
a="hello"
res=[]
for i in a:
  if i not in res:
    res.append(i)
print(res)

['h', 'e', 'l', 'o']


In [ ]:
a="hello"
res=" "
for i in a:
  res=i+res
  print(res)

h 
eh 
leh 
lleh 
olleh 


In [ ]:
s=("chennai",101,"tnagar",102)
letters=[]
digits=[]
for i in s:
  if isinstance(i,int):
    digits.append(i)
  else:
    letters.append(i)
print(letters)
print(digits)

['chennai', 'tnagar']
[101, 102]


In [ ]:
class Dog:
  def __init__(self,name,sound,color):
    self.name=name
    self._sound=sound
    self.__color=color

  # def display(self):
  #   print(f"{self.name},{self._sound}")
  def get_color(self):
    return self.__color

  def set_color(self,color):
    self.__color=color
    print(self.__color)

obj=Dog("buddy","lol","black")
obj.name
obj._sound

# obj.display()
obj.set_color("white")


white


23.09.2025

In [ ]:
# To print missing value
arr=[1,2,3,5]
n=len(arr)+1
cal=(n*(n+1)//2)
# print(cal)
sum=0
for i in arr:
  sum+=i
# print(sum)

missingval=cal-sum
print(missingval)


4


In [ ]:
# to print the array duplicates
arr=[1,2,3,2,3]
dictt={}
for i in arr:
  if i not in dictt:
    dictt[i]=1
  else:
    dictt[i]+=1
print(dictt)
res=[]
for j in dictt:
  if dictt[j]>1:
    res.append(j)
    j+=1
print(res)

{1: 1, 2: 2, 3: 2}
[2, 3]


In [ ]:
# string prob
s = "i.like.this.program.very.much"
word=s.split(".")
#
word.reverse()
print(word)
result=".".join(word)
print(result)


['much', 'very', 'program', 'this', 'like', 'i']
much.very.program.this.like.i


In [ ]:
a=6
res=[]
for i in range(1,a+1):
  if a%i==0:
    res.append(i)
print(res)


[1, 2, 3, 6]


In [ ]:
import numpy as np
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])
print(cube)
print(cube.ndim)
print(cube.shape)
print(cube.size)
print(cube[1,2,0])
print(cube.reshape(-1,2))
print(cube.reshape(6,3))
print(cube.reshape(3,3,2))
print(np.sum(cube))
print(np.mean(cube,axis=0))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3
(2, 3, 3)
18
16
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
171
[[ 5.5  6.5  7.5]
 [ 8.5  9.5 10.5]
 [11.5 12.5 13.5]]


In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x*y)
print(np.pow(x,y))
print(np.sum(x))
print(np.sum(y))
print(np.min(x))
print(np.mean(y))

[5 7 9]
[ 4 10 18]
[  1  32 729]
6
15
1
5.0


In [ ]:
s="mollyom"
print(len(s))
l=0
r=len(s)-1
while l<r:
  if s[l]!=s[r]:
    print("not palindrome")
    break
  l+=1
  r-=1
else:
    print("palindrome")

7
not palindrome


In [ ]:
a="nhjg"
rev="".join(reversed(a))
print(rev)

gjhn


In [ ]:
a="listeen"
b="silent"
c=sorted(a)
d=sorted(b)
if c==d:
  print("anagram")
else:
  print("not a anagram")

not a anagram


9/10/2025

In [ ]:
s="(){}({])"
st=[]
d={"(":")","[":"]","{":"}"}
for i in s:
  if i in d.keys():
    st.append(i)
  else:
    if st==[]:
      print("invalid")
    else:
      if d[st[-1]]==i:
        st.pop()
      else:
        break
if st==[]:
  print("valid parenthesis")
else:
  print("invalid parenthesis")



invalid parenthesis


In [ ]:
n=[0,0,1,1,2,3,3,4,4,5,5]
l=1
for r in range(1,len(n)):
  if n[r]!=n[r-1]:
    n[l]=n[r]
    l+=1
print(n)
print(n[:l])


[0, 1, 2, 3, 4, 5, 3, 4, 4, 5, 5]
[0, 1, 2, 3, 4, 5]


In [ ]:
def resolve(pkg, deps):
    if pkg not in deps or not deps[pkg]:
        print(pkg)
        return
    for d in deps[pkg]:
        resolve(d, deps)
    print(pkg)

dependencies = {
    "app": ["core", "ui"],
    "core": ["utils", "network"],
    "utils": [],
    "network": ["security"],
    "ui": ["theme"],
    "security": [],
    "theme": []
}

resolve("app", dependencies)


utils
security
network
core
theme
ui
app


12-10-2025


In [ ]:
# to print min and max value
arr=[1,4,3,0,10,-1,8,9,8,6]
mini=0
maxi=0
for i in arr:
  if i < mini:
    mini=i
  elif i > maxi:
    maxi=i
print(maxi)
print(mini)

10
-1


In [ ]:
arr=[2,4,1,3,5]
first=arr[0]
second=arr[0]
third=arr[0]
for i in arr:
  if i>first:
    third=second
    second=first
    first=i
  elif i>second:
    third=second
    second=i
  elif i>third:
    third=i
print(first)
print(second)
print(third)


5
4
3
